version: "3.3"

services:
  http:
    build:
      context: ${COMPOSE_ROOT}/services/http
      dockerfile: Dockerfile
    volumes:
      - type: bind
        source: ${COMPOSE_ROOT}/data/sites/
        target: /var/www/sites/
      - type: bind
        source: ${COMPOSE_ROOT}/data/caddy/caddypath/
        target: /var/caddy/
      - type: bind
        source: ${COMPOSE_ROOT}/services/http/Caddyfile
        target: /etc/Caddyfile
    environment:
      CADDYPATH: "/var/caddy"
    ports:
      - "443:443"
      - "80:80"
    restart: always
